# Generated by Django 3.0.7 on 2020-08-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200821_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jonctionetapesuivi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jonctionutilisateuretude',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refcontrolequalite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refetapeetude',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refetatetape',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refetudes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='Centre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='suiviupload',
            options={},
        ),
        migrations.AddField(
            model_name='suiviupload',
            name='fichiers',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterModelTable(
            name='jonctionetapesuivi',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jonctionutilisateuretude',
            table=None,
        ),
        migrations.AlterModelTable(
            name='refcontrolequalite',
            table=None,
        ),
        migrations.AlterModelTable(
            name='refetapeetude',
            table=None,
        ),
        migrations.AlterModelTable(
            name='refetatetape',
            table=None,
        ),
        migrations.AlterModelTable(
            name='refetudes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='Centre',
            table=None,
        ),
        migrations.AlterModelTable(
            name='suiviupload',
            table=None,
        ),
    ]