# Generated by Django 3.0.7 on 2020-09-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20200917_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierupload',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.SuiviUpload'),
        ),
    ]
