# Generated by Django 3.0.7 on 2020-09-29 10:35

from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_suividocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suividocument',
            name='etude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.RefEtudes'),
        ),
        migrations.AlterField(
            model_name='suividocument',
            name='fichiers',
            field=models.FileField(null=True, upload_to=upload.models.doc_directory_path),
        ),
    ]
