# Generated by Django 3.0.7 on 2020-10-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_log_reftypeaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='info',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
