# Generated by Django 3.0.7 on 2020-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_auto_20201015_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=3000)),
                ('prenom', models.CharField(max_length=3000)),
                ('courriel', models.CharField(max_length=3000)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('poste', models.CharField(max_length=3000)),
            ],
        ),
    ]
