# Generated by Django 3.0.7 on 2020-10-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0019_auto_20201029_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
