# Generated by Django 3.0.7 on 2021-04-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_refetatvalide_refetatvalidecompte_validecompte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefEtatValide',
        ),
    ]
