# Generated by Django 3.0.7 on 2021-04-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0023_auto_20210427_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validecompte',
            old_name='compte_valide',
            new_name='create_user',
        ),
    ]
