# Generated by Django 3.0.7 on 2021-04-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0024_auto_20210427_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validecompte',
            name='etat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.RefEtatValideCompte'),
        ),
    ]
