# Generated by Django 4.0.4 on 2022-06-22 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=3000)),
                ('prenom', models.CharField(max_length=3000)),
                ('courriel', models.CharField(max_length=3000)),
                ('telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('poste', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='DossierUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date de création')),
            ],
        ),
        migrations.CreateModel(
            name='JonctionUtilisateurEtude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_autorisation', models.DateTimeField(verbose_name="Date d'autorisation")),
            ],
        ),
        migrations.CreateModel(
            name='RefControleQualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='RefEtatEtape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='RefEtatValideCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='RefEtudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5000)),
                ('date_ouverture', models.DateTimeField(verbose_name="Date d'ouverture")),
            ],
        ),
        migrations.CreateModel(
            name='RefTypeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ValideCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crea', models.DateTimeField(null=True, verbose_name='Date de la creation')),
                ('date_demande', models.DateTimeField(blank=True, null=True, verbose_name='Date de la demande')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_edit', models.DateTimeField(blank=True, null=True, verbose_name="Date d'une édition")),
                ('create_user', models.OneToOneField(db_column='Compte_Valider', on_delete=django.db.models.deletion.CASCADE, related_name='Compte_Valider', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demandeur_edit', models.ForeignKey(blank=True, db_column='editeur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editeur', to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.refetatvalidecompte')),
                ('validateur', models.ForeignKey(blank=True, db_column='validateur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_patient', models.CharField(max_length=5000)),
                ('date_upload', models.DateTimeField(verbose_name="Date d'envois")),
                ('date_examen', models.DateTimeField(verbose_name='Date examen')),
                ('fichiers', models.FileField(null=True, upload_to=upload.models.user_directory_path)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.dossierupload')),
                ('etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.jonctionutilisateuretude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('fichiers', models.FileField(null=True, upload_to=upload.models.doc_directory_path)),
                ('background', models.CharField(blank=True, max_length=5000, null=True)),
                ('etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.refetudes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefInfoCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5000)),
                ('numero', models.IntegerField(blank=True)),
                ('date_ajout', models.DateTimeField(verbose_name="Date d'ajout")),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefEtapeEtude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5000)),
                ('etude', models.ManyToManyField(to='upload.refetudes')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('info', models.CharField(blank=True, max_length=5000, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.reftypeaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jonctionutilisateuretude',
            name='etude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.refetudes'),
        ),
        migrations.AddField(
            model_name='jonctionutilisateuretude',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JonctionEtapeSuivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'étape")),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.refetapeetude')),
                ('etat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.refetatetape')),
                ('upload', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='upload.dossierupload')),
            ],
        ),
        migrations.AddField(
            model_name='dossierupload',
            name='controle_qualite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.refcontrolequalite'),
        ),
        migrations.AddField(
            model_name='dossierupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
