# Generated by Django 3.0.7 on 2020-07-28 12:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favoris',
            new_name='UtilisateurProtocole',
        ),
        migrations.RenameField(
            model_name='utilisateurprotocole',
            old_name='produits',
            new_name='protocole',
        ),
    ]
