# Generated by Django 3.0.7 on 2020-08-31 14:54

from django.conf import settings
from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0003_auto_20200821_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refinfocentre',
            name='user',
        ),
        migrations.AddField(
            model_name='refinfocentre',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suiviupload',
            name='fichiers',
            field=models.FileField(null=True, upload_to=upload.models.user_directory_path),
        ),
    ]
