# Generated by Django 3.0.7 on 2020-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200831_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinfocentre',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
    ]
