# Generated by Django 3.0.7 on 2020-09-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20200917_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jonctionetapesuivi',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de l'étape"),
        ),
    ]
