# Generated by Django 3.0.7 on 2020-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_auto_20200929_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='suividocument',
            name='background',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
