# Generated by Django 3.0.7 on 2020-10-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20201006_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jonctionetapesuivi',
            name='etat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.RefEtatEtape'),
        ),
    ]
