# Generated by Django 3.0.7 on 2021-04-27 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0022_delete_refetatvalide'),
    ]

    operations = [
        migrations.AddField(
            model_name='validecompte',
            name='date_crea',
            field=models.DateTimeField(null=True, verbose_name='Date de la creation'),
        ),
        migrations.AlterField(
            model_name='validecompte',
            name='compte_valide',
            field=models.OneToOneField(db_column='Compte_Valider', on_delete=django.db.models.deletion.CASCADE, related_name='Compte_Valider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validecompte',
            name='date_demande',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de la demande'),
        ),
        migrations.AlterField(
            model_name='validecompte',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='validecompte',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
