# Generated by Django 3.0.7 on 2021-04-27 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0027_auto_20210427_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='validecompte',
            name='date_edit',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'une édition"),
        ),
        migrations.AddField(
            model_name='validecompte',
            name='demandeur_edit',
            field=models.ForeignKey(blank=True, db_column='editeur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editeur', to=settings.AUTH_USER_MODEL),
        ),
    ]
